(lts.ruleset
;  Name of rule set
  gogepen
;  Sets used in the rules
(
  ( C b c d f g h j k l m n p q r s t v x z "'" )
  ( Q b c d f g h j k l m n p q r s t v x z "'" )
  ( W b c d f g h j k l m n p q r s t v w x z "'" )
  ( K b c d f g h j k m n p q r s t v x z "'" )  
  ( V a e i o u y )
  ( M l m n r )
  ( R l n r )
  ( N n r f )
  ( F l n r f )
  ( P p t c b d g ff f th x h s f dh mh nh ngh m n ng ll r rh rw w "'" )
  ( X a e o u ae ai au ei eu oe oi ou aw ew ow uw ay ey oy aay y i iw )
  ( Y p t c b d f dd m n "-" "'" )
  ( Z p t c d m n ng "-" "'" )
  ( H b g p ff f th t dd d s sb st sg ch c m n ng "'" )
  ( U "-" # )

;; Variables used originally in "newwelstr" and needed for the yod rules
  ( T a e i o u w y )
  ( D a e i o u w y )
  ( L a e i o u y )
  ( I a e o )
  
  ( A b c d f g h j k l m n p q r s t v w x z "\"" "%" "\\" "'" )
  ( B b c d f g h j k l m n p q r s t v w x z "\"" "%" "\\" "'" )
  ( E b c d f g h j k l m n p q r s t v x z "\"" "%" "\\" "'" )  
  ( S b c d f g h j k l m n p q r s t v x z "\"" "%" "\\" "'" )
  ( G b c d f g h j k l m n p q r s t v x z "\"" "%" "\\" "'" )  
  
  
  
)
;  Rules
(

; 	Rules for determining epenthetic vowels etc
; 	-------------------------------------------

;   # symbols


;   # variables

;   C    one or more of [b c d f g h j k l m n p q r s t v x z]
;   Q    [b c d f g h j k l m n p q r s t v x z]
;   W    one or more of [b c d f g h j k l m n p q r s t v w x z]  
;   V    [a e i o u y]
;   M    zero or one of [l m n r]
;   R    [l n r]
;   F    [l n r f]
;   P    [p t c b d g ff f th x h s f dh mh nh ngh m n ng ll r rh rw w]
;   X    [a e o u ae ai au ei eu oe oi ou aw ew ow uw ay ey oy aay y i iw]
;   Y    [p t c b d f dd m n]
;   Z    [p t c d m n ng]
;   H    [b g p ff f th t dd d s sb st sg ch c m n ng]

;   # end symbols

;; X = /ch/ (voiceless palato-alveolar affricate)
;; S = /sh/ (voiceless palato-alveolar fricative)

( [ "-" ] = "-" )
( [ "'" ] = )

( [ t s i ] V = X )
( U [ s i ] V = S )

( [ q ] u = k )
( q [ u ] V U = )
( q [ u ] V = w )


;    Put lexical exceptions first of all:

( [ a n g o s ] = a n g g o s )
( [ a r a t o i ] U = a r a t o / i )
( U h [ e n ] U = e ^ n )
( U [ y m y l ] U = y m y / l )
( U [ y m y s g ] U = y m y / s g )
( U [ y n g h y d ] U = y n g h y / d )
( V C + [ h a u ] U = h a / u )
( w C + [ h a u ] U = h a / u )
( V w [ h a u ] U = h a / u )

;    Now add epenthetic vowels

( o e M [ b ] F U = b y )
( o e [ b ] F U = b y )
( a e M [ b ] F U = b y )
( a e [ b ] F U = b y )
( o e M [ g ] F U = g y )
( o e [ g ] F U = g y )
( a e M [ g ] F U = g y )
( a e [ g ] F U = g y )
( o e M [ p ] F U = p y )
( o e [ p ] F U = p y )
( a e M [ p ] F U = p y )
( a e [ p ] F U = p y )
( o e M [ f f ] F U = f f y )
( o e [ f f ] F U = f f y )
( a e M [ f f ] F U = f f y )
( a e [ f f ] F U = f f y )
( o e M [ f ] R U = f y )
( o e [ f ] R U = f y )
( a e M [ f ] R U = f y )
( a e [ f ] R U = f y )
( o e M [ t h ] F U = t h y )
( o e [ t h ] F U = t h y )
( a e M [ t h ] F U = t h y )
( a e [ t h ] F U = t h y )
( o e M [ t h ] m U = t h y )
( o e [ t h ] m U = t h y )
( a e M [ t h ] m U = t h y )
( a e [ t h ] m U = t h y )
( o e M [ t ] F U = t y )
( o e [ t ] F U = t y )
( a e M [ t ] F U = t y )
( a e [ t ] F U = t y )
( o e l l [ t ] F U = t y )
( a e l l [ t ] F U = t y )
( o e M [ d d ] F U = d d y )
( o e [ d d ] F U = d d y )
( a e M [ d d ] F U = d d y )
( a e [ d d ] F U = d d y )
( o e M [ d ] F U = d y )
( o e [ d ] F U = d y )
( a e M [ d ] F U = d y )
( a e [ d ] F U = d y )
( o e M [ s ] F U = s y )
( o e [ s ] F U = s y )
( a e M [ s ] F U = s y )
( a e [ s ] F U = s y )
( o e M [ s b ] F U = s b y )
( o e [ s b ] F U = s b y )
( a e M [ s b ] F U = s b y )
( a e [ s b ] F U = s b y )
( o e M [ s t ] F U = s t y )
( o e [ s t ] F U = s t y )
( a e M [ s t ] F U = s t y )
( a e [ s t ] F U = s t y )
( o e M [ s g ] F U = s g y )
( o e [ s g ] F U = s g y )
( a e M [ s g ] F U = s g y )
( a e [ s g ] F U = s g y )
( o e M [ c h ] F U = c h y )
( o e [ c h ] F U = c h y )
( a e M [ c h ] F U = c h y )
( a e [ c h ] F U = c h y )
( o e M [ c ] F U = c y )
( o e [ c ] F U = c y )
( a e M [ c ] F U = c y )
( a e [ c ] F U = c y )
( o e M [ m ] l U = m y )
( o e [ m ] l U = m y )
( a e M [ m ] l U = m y )
( a e [ m ] l U = m y )
( o e M [ n ] l U = n y )
( o e [ n ] l U = n y )
( a e M [ n ] l U = n y )
( a e [ n ] l U = n y )
( o e M [ n g ] l U = n g y )
( o e [ n g ] l U = n g y )
( a e M [ n g ] l U = n g y )
( a e [ n g ] l U = n g y )

( i M [ b ] F U = b i )
( i [ b ] F U = b i )
( e M [ b ] F U = b e )
( e [ b ] F U = b e )
( a M [ b ] F U = b a )
( a [ b ] F U = b a )
( o M [ b ] F U = b o )
( o [ b ] F U = b o )
( w M [ b ] F U = b w )
( w [ b ] F U = b w )
( u M [ b ] F U = b y )
( u [ b ] F U = b y )
( y M [ b ] F U = b y )
( y [ b ] F U = b y )
( i M [ g ] F U = g i )
( i [ g ] F U = g i )
( e M [ g ] F U = g e )
( e [ g ] F U = g e )
( a M [ g ] F U = g a )
( a [ g ] F U = g a )
( o M [ g ] F U = g o )
( o [ g ] F U = g o )
( w M [ g ] F U = g w )
( w [ g ] F U = g w )
( u M [ g ] F U = g y )
( u [ g ] F U = g y )
( y M [ g ] F U = g y )
( y [ g ] F U = g y )
( i M [ p ] F U = p i )
( i [ p ] F U = p i )
( e M [ p ] F U = p e )
( e [ p ] F U = p e )
( a M [ p ] F U = p a )
( a [ p ] F U = p a )
( o M [ p ] F U = p o )
( o [ p ] F U = p o )
( w M [ p ] F U = p w )
( w [ p ] F U = p w )
( u M [ p ] F U = p y )
( u [ p ] F U = p y )
( y M [ p ] F U = p y )
( y [ p ] F U = p y )
( i M [ f f ] F U = f f i )
( i [ f f ] F U = f f i )
( e M [ f f ] F U = f f e )
( e [ f f ] F U = f f e )
( a M [ f f ] F U = f f a )
( a [ f f ] F U = f f a )
( o M [ f f ] F U = f f o )
( o [ f f ] F U = f f o )
( w M [ f f ] F U = f f w )
( w [ f f ] F U = f f w )
( u M [ f f ] F U = f f y )
( u [ f f ] F U = f f y )
( y M [ f f ] F U = f f y )
( y [ f f ] F U = f f y )
( i M [ f ] R U = f i )
( i [ f ] R U = f i )
( e M [ f ] R U = f e )
( e [ f ] R U = f e )
( a M [ f ] R U = f a )
( a [ f ] R U = f a )
( o M [ f ] R U = f o )
( o [ f ] R U = f o )
( w M [ f ] R U = f w )
( w [ f ] R U = f w )
( u M [ f ] R U = f y )
( u [ f ] R U = f y )
( y M [ f ] R U = f y )
( y [ f ] R U = f y )
( i M [ t h ] F U = t h i )
( i [ t h ] F U = t h i )
( e M [ t h ] F U = t h e )
( e [ t h ] F U = t h e )
( a M [ t h ] F U = t h a )
( a [ t h ] F U = t h a )
( o M [ t h ] F U = t h o )
( o [ t h ] F U = t h o )
( w M [ t h ] F U = t h w )
( w [ t h ] F U = t h w )
( u M [ t h ] F U = t h y )
( u [ t h ] F U = t h y )
( y M [ t h ] F U = t h y )
( y [ t h ] F U = t h y )
( i M [ t h ] m U = t h i )
( i [ t h ] m U = t h i )
( e M [ t h ] m U = t h e )
( e [ t h ] m U = t h e )
( a M [ t h ] m U = t h a )
( a [ t h ] m U = t h a )
( o M [ t h ] m U = t h o )
( o [ t h ] m U = t h o )
( w M [ t h ] m U = t h w )
( w [ t h ] m U = t h w )
( u M [ t h ] m U = t h y )
( u [ t h ] m U = t h y )
( y M [ t h ] m U = t h y )
( y [ t h ] m U = t h y )
( i M [ t ] F U = t i )
( i [ t ] F U = t i )
( e M [ t ] F U = t e )
( e [ t ] F U = t e )
( a M [ t ] F U = t a )
( a [ t ] F U = t a )
( o M [ t ] F U = t o )
( o [ t ] F U = t o )
( w M [ t ] F U = t w )
( w [ t ] F U = t w )
( u M [ t ] F U = t y )
( u [ t ] F U = t y )
( y M [ t ] F U = t y )
( y [ t ] F U = t y )
( i l l [ t ] F U = t i )
( e l l [ t ] F U = t e )
( a l l [ t ] F U = t a )
( o l l [ t ] F U = t o )
( w l l [ t ] F U = t w )
( u l l [ t ] F U = t y )
( y l l [ t ] F U = t y )
( i M [ d d ] F U = d d i )
( i [ d d ] F U = d d i )
( e M [ d d ] F U = d d e )
( e [ d d ] F U = d d e )
( a M [ d d ] F U = d d a )
( a [ d d ] F U = d d a )
( o M [ d d ] F U = d d o )
( o [ d d ] F U = d d o )
( w M [ d d ] F U = d d w )
( w [ d d ] F U = d d w )
( u M [ d d ] F U = d d y )
( u [ d d ] F U = d d y )
( y M [ d d ] F U = d d y )
( y [ d d ] F U = d d y )
( i M [ d ] F U = d i )
( i [ d ] F U = d i )
( e M [ d ] F U = d e )
( e [ d ] F U = d e )
( a M [ d ] F U = d a )
( a [ d ] F U = d a )
( o M [ d ] F U = d o )
( o [ d ] F U = d o )
( w M [ d ] F U = d w )
( w [ d ] F U = d w )
( u M [ d ] F U = d y )
( u [ d ] F U = d y )
( y M [ d ] F U = d y )
( y [ d ] F U = d y )
( i M [ s ] F U = s i )
( i [ s ] F U = s i )
( e M [ s ] F U = s e )
( e [ s ] F U = s e )
( a M [ s ] F U = s a )
( a [ s ] F U = s a )
( o M [ s ] F U = s o )
( o [ s ] F U = s o )
( w M [ s ] F U = s w )
( w [ s ] F U = s w )
( u M [ s ] F U = s y )
( u [ s ] F U = s y )
( y M [ s ] F U = s y )
( y [ s ] F U = s y )
( i M [ s b ] F U = s b i )
( i [ s b ] F U = s b i )
( e M [ s b ] F U = s b e )
( e [ s b ] F U = s b e )
( a M [ s b ] F U = s b a )
( a [ s b ] F U = s b a )
( o M [ s b ] F U = s b o )
( o [ s b ] F U = s b o )
( w M [ s b ] F U = s b w )
( w [ s b ] F U = s b w )
( u M [ s b ] F U = s b y )
( u [ s b ] F U = s b y )
( y M [ s b ] F U = s b y )
( y [ s b ] F U = s b y )
( i M [ s t ] F U = s t i )
( i [ s t ] F U = s t i )
( e M [ s t ] F U = s t e )
( e [ s t ] F U = s t e )
( a M [ s t ] F U = s t a )
( a [ s t ] F U = s t a )
( o M [ s t ] F U = s t o )
( o [ s t ] F U = s t o )
( w M [ s t ] F U = s t w )
( w [ s t ] F U = s t w )
( u M [ s t ] F U = s t y )
( u [ s t ] F U = s t y )
( y M [ s t ] F U = s t y )
( y [ s t ] F U = s t y )
( i M [ s g ] F U = s g i )
( i [ s g ] F U = s g i )
( e M [ s g ] F U = s g e )
( e [ s g ] F U = s g e )
( a M [ s g ] F U = s g a )
( a [ s g ] F U = s g a )
( o M [ s g ] F U = s g o )
( o [ s g ] F U = s g o )
( w M [ s g ] F U = s g w )
( w [ s g ] F U = s g w )
( u M [ s g ] F U = s g y )
( u [ s g ] F U = s g y )
( y M [ s g ] F U = s g y )
( y [ s g ] F U = s g y )
( i M [ c h ] F U = c h i )
( i [ c h ] F U = c h i )
( e M [ c h ] F U = c h e )
( e [ c h ] F U = c h e )
( a M [ c h ] F U = c h a )
( a [ c h ] F U = c h a )
( o M [ c h ] F U = c h o )
( o [ c h ] F U = c h o )
( w M [ c h ] F U = c h w )
( w [ c h ] F U = c h w )
( u M [ c h ] F U = c h y )
( u [ c h ] F U = c h y )
( y M [ c h ] F U = c h y )
( y [ c h ] F U = c h y )
( i M [ c ] F U = c i )
( i [ c ] F U = c i )
( e M [ c ] F U = c e )
( e [ c ] F U = c e )
( a M [ c ] F U = c a )
( a [ c ] F U = c a )
( o M [ c ] F U = c o )
( o [ c ] F U = c o )
( w M [ c ] F U = c w )
( w [ c ] F U = c w )
( u M [ c ] F U = c y )
( u [ c ] F U = c y )
( y M [ c ] F U = c y )
( y [ c ] F U = c y )
( i M [ m ] l U = m i )
( i [ m ] l U = m i )
( e M [ m ] l U = m e )
( e [ m ] l U = m e )
( a M [ m ] l U = m a )
( a [ m ] l U = m a )
( o M [ m ] l U = m o )
( o [ m ] l U = m o )
( w M [ m ] l U = m w )
( w [ m ] l U = m w )
( u M [ m ] l U = m y )
( u [ m ] l U = m y )
( y M [ m ] l U = m y )
( y [ m ] l U = m y )
( i M [ n ] l U = n i )
( i [ n ] l U = n i )
( e M [ n ] l U = n e )
( e [ n ] l U = n e )
( a M [ n ] l U = n a )
( a [ n ] l U = n a )
( o M [ n ] l U = n o )
( o [ n ] l U = n o )
( w M [ n ] l U = n w )
( w [ n ] l U = n w )
( u M [ n ] l U = n y )
( u [ n ] l U = n y )
( y M [ n ] l U = n y )
( y [ n ] l U = n y )
( i M [ n g ] l U = n g i )
( i [ n g ] l U = n g i )
( e M [ n g ] l U = n g e )
( e [ n g ] l U = n g e )
( a M [ n g ] l U = n g a )
( a [ n g ] l U = n g a )
( o M [ n g ] l U = n g o )
( o [ n g ] l U = n g o )
( w M [ n g ] l U = n g w )
( w [ n g ] l U = n g w )
( u M [ n g ] l U = n g y )
( u [ n g ] l U = n g y )
( y M [ n g ] l U = n g y )
( y [ n g ] l U = n g y )

;;; Non-word-final context
;;; BJW Jan 2006: substitute N (no "l") instead of F, and add extra case of "l K"
;;; to avoid cases of "blaenllaw" firing as if "ll" were two consonants.
;;;  ( Q b c d f g h j k l m n p q r s t v x z "'" )
;;;  ( K b c d f g h j k m n p q r s t v x z "'" )  
;;;  ( M l m n r )
;;;  ( R l n r )
;;;  ( F l n r f )
;;;  ( N n r f )
;;;
;;;( o e M [ b ] N Q + = b y )
;;;( o e [ b ] N Q + = b y )
;;;( a e M [ b ] N Q + = b y )
;;;( a e [ b ] N Q + = b y )
;;;( o e M [ g ] N Q + = g y )
;;;( o e [ g ] N Q + = g y )
;;;( a e M [ g ] N Q + = g y )
;;;( a e [ g ] N Q + = g y )
;;;( o e M [ p ] N Q + = p y )
;;;( o e [ p ] N Q + = p y )
;;;( a e M [ p ] N Q + = p y )
;;;( a e [ p ] N Q + = p y )
;;;( o e M [ f f ] N Q + = f f y )
;;;( o e [ f f ] N Q + = f f y )
;;;( a e M [ f f ] N Q + = f f y )
;;;( a e [ f f ] N Q + = f f y )
;;;( o e M [ f ] R Q + = f y )
;;;( o e [ f ] R Q + = f y )
;;;( a e M [ f ] R Q + = f y )
;;;( a e [ f ] R Q + = f y )
;;;( o e M [ t h ] N Q + = t h y )
;;;( o e [ t h ] N Q + = t h y )
;;;( a e M [ t h ] N Q + = t h y )
;;;( a e [ t h ] N Q + = t h y )
;;;( o e M [ t h ] m Q + = t h y )
;;;( o e [ t h ] m Q + = t h y )
;;;( a e M [ t h ] m Q + = t h y )
;;;( a e [ t h ] m Q + = t h y )
;;;( o e M [ t ] N Q + = t y )
;;;( o e [ t ] N Q + = t y )
;;;( a e M [ t ] N Q + = t y )
;;;( a e [ t ] N Q + = t y )
;;;( o e l l [ t ] N Q + = t y )
;;;( a e l l [ t ] N Q + = t y )
;;;( o e M [ d d ] N Q + = d d y )
;;;( o e [ d d ] N Q + = d d y )
;;;( a e M [ d d ] N Q + = d d y )
;;;( a e [ d d ] N Q + = d d y )
;;;( o e M [ d ] N Q + = d y )
;;;( o e [ d ] N Q + = d y )
;;;( a e M [ d ] N Q + = d y )
;;;( a e [ d ] N Q + = d y )
;;;( o e M [ s ] N Q + = s y )
;;;( o e [ s ] N Q + = s y )
;;;( a e M [ s ] N Q + = s y )
;;;( a e [ s ] N Q + = s y )
;;;( o e M [ s b ] N Q + = s b y )
;;;( o e [ s b ] N Q + = s b y )
;;;( a e M [ s b ] N Q + = s b y )
;;;( a e [ s b ] N Q + = s b y )
;;;( o e M [ s t ] N Q + = s t y )
;;;( o e [ s t ] N Q + = s t y )
;;;( a e M [ s t ] N Q + = s t y )
;;;( a e [ s t ] N Q + = s t y )
;;;( o e M [ s g ] N Q + = s g y )
;;;( o e [ s g ] N Q + = s g y )
;;;( a e M [ s g ] N Q + = s g y )
;;;( a e [ s g ] N Q + = s g y )
;;;( o e M [ c h ] N Q + = c h y )
;;;( o e [ c h ] N Q + = c h y )
;;;( a e M [ c h ] N Q + = c h y )
;;;( a e [ c h ] N Q + = c h y )
;;;( o e M [ c ] N Q + = c y )
;;;( o e [ c ] N Q + = c y )
;;;( a e M [ c ] N Q + = c y )
;;;( a e [ c ] N Q + = c y )
;;;( o e M [ m ] N Q + = m y )
;;;( o e [ m ] N Q + = m y )
;;;( a e M [ m ] N Q + = m y )
;;;( a e [ m ] N Q + = m y )
;;;( o e M [ n ] N Q + = n y )
;;;( o e [ n ] N Q + = n y )
;;;( a e M [ n ] N Q + = n y )
;;;( a e [ n ] N Q + = n y )
;;;( o e M [ n g ] N Q + = n g y )
;;;( o e [ n g ] N Q + = n g y )
;;;( a e M [ n g ] N Q + = n g y )
;;;( a e [ n g ] N Q + = n g y )
;;;
;;;( i M [ b ] N Q + = b i )
;;;( i [ b ] N Q + = b i )
;;;( e M [ b ] N Q + = b e )
;;;( e [ b ] N Q + = b e )
;;;( a M [ b ] N Q + = b a )
;;;( a [ b ] N Q + = b a )
;;;( o M [ b ] N Q + = b o )
;;;( o [ b ] N Q + = b o )
;;;( w M [ b ] N Q + = b w )
;;;( w [ b ] N Q + = b w )
;;;( u M [ b ] N Q + = b y )
;;;( u [ b ] N Q + = b y )
;;;( y M [ b ] N Q + = b y )
;;;( y [ b ] N Q + = b y )
;;;( i M [ g ] N Q + = g i )
;;;( i [ g ] N Q + = g i )
;;;( e M [ g ] N Q + = g e )
;;;( e [ g ] N Q + = g e )
;;;( a M [ g ] N Q + = g a )
;;;( a [ g ] N Q + = g a )
;;;( o M [ g ] N Q + = g o )
;;;( o [ g ] N Q + = g o )
;;;( w M [ g ] N Q + = g w )
;;;( w [ g ] N Q + = g w )
;;;( u M [ g ] N Q + = g y )
;;;( u [ g ] N Q + = g y )
;;;( y M [ g ] N Q + = g y )
;;;( y [ g ] N Q + = g y )
;;;( i M [ p ] N Q + = p i )
;;;( i [ p ] N Q + = p i )
;;;( e M [ p ] N Q + = p e )
;;;( e [ p ] N Q + = p e )
;;;( a M [ p ] N Q + = p a )
;;;( a [ p ] N Q + = p a )
;;;( o M [ p ] N Q + = p o )
;;;( o [ p ] N Q + = p o )
;;;( w M [ p ] N Q + = p w )
;;;( w [ p ] N Q + = p w )
;;;( u M [ p ] N Q + = p y )
;;;( u [ p ] N Q + = p y )
;;;( y M [ p ] N Q + = p y )
;;;( y [ p ] N Q + = p y )
;;;( i M [ f f ] N Q + = f f i )
;;;( i [ f f ] N Q + = f f i )
;;;( e M [ f f ] N Q + = f f e )
;;;( e [ f f ] N Q + = f f e )
;;;( a M [ f f ] N Q + = f f a )
;;;( a [ f f ] N Q + = f f a )
;;;( o M [ f f ] N Q + = f f o )
;;;( o [ f f ] N Q + = f f o )
;;;( w M [ f f ] N Q + = f f w )
;;;( w [ f f ] N Q + = f f w )
;;;( u M [ f f ] N Q + = f f y )
;;;( u [ f f ] N Q + = f f y )
;;;( y M [ f f ] N Q + = f f y )
;;;( y [ f f ] N Q + = f f y )
;;;( i M [ f ] R Q + = f i )
;;;( i [ f ] R Q + = f i )
;;;( e M [ f ] R Q + = f e )
;;;( e [ f ] R Q + = f e )
;;;( a M [ f ] R Q + = f a )
;;;( a [ f ] R Q + = f a )
;;;( o M [ f ] R Q + = f o )
;;;( o [ f ] R Q + = f o )
;;;( w M [ f ] R Q + = f w )
;;;( w [ f ] R Q + = f w )
;;;( u M [ f ] R Q + = f y )
;;;( u [ f ] R Q + = f y )
;;;( y M [ f ] R Q + = f y )
;;;( y [ f ] R Q + = f y )
;;;( i M [ t h ] N Q + = t h i )
;;;( i [ t h ] N Q + = t h i )
;;;( e M [ t h ] N Q + = t h e )
;;;( e [ t h ] N Q + = t h e )
;;;( a M [ t h ] N Q + = t h a )
;;;( a [ t h ] N Q + = t h a )
;;;( o M [ t h ] N Q + = t h o )
;;;( o [ t h ] N Q + = t h o )
;;;( w M [ t h ] N Q + = t h w )
;;;( w [ t h ] N Q + = t h w )
;;;( u M [ t h ] N Q + = t h y )
;;;( u [ t h ] N Q + = t h y )
;;;( y M [ t h ] N Q + = t h y )
;;;( y [ t h ] N Q + = t h y )
;;;( i M [ t h ] m Q + = t h i )
;;;( i [ t h ] m Q + = t h i )
;;;( e M [ t h ] m Q + = t h e )
;;;( e [ t h ] m Q + = t h e )
;;;( a M [ t h ] m Q + = t h a )
;;;( a [ t h ] m Q + = t h a )
;;;( o M [ t h ] m Q + = t h o )
;;;( o [ t h ] m Q + = t h o )
;;;( w M [ t h ] m Q + = t h w )
;;;( w [ t h ] m Q + = t h w )
;;;( u M [ t h ] m Q + = t h y )
;;;( u [ t h ] m Q + = t h y )
;;;( y M [ t h ] m Q + = t h y )
;;;( y [ t h ] m Q + = t h y )
;;;( i M [ t ] N Q + = t i )
;;;( i [ t ] N Q + = t i )
;;;( e M [ t ] N Q + = t e )
;;;( e [ t ] N Q + = t e )
;;;( a M [ t ] N Q + = t a )
;;;( a [ t ] N Q + = t a )
;;;( o M [ t ] N Q + = t o )
;;;( o [ t ] N Q + = t o )
;;;( w M [ t ] N Q + = t w )
;;;( w [ t ] N Q + = t w )
;;;( u M [ t ] N Q + = t y )
;;;( u [ t ] N Q + = t y )
;;;( y M [ t ] N Q + = t y )
;;;( y [ t ] N Q + = t y )
;;;( i l l [ t ] N Q + = t i )
;;;( e l l [ t ] N Q + = t e )
;;;( a l l [ t ] N Q + = t a )
;;;( o l l [ t ] N Q + = t o )
;;;( w l l [ t ] N Q + = t w )
;;;( u l l [ t ] N Q + = t y )
;;;( y l l [ t ] N Q + = t y )
;;;( i M [ d d ] N Q + = d d i )
;;;( i [ d d ] N Q + = d d i )
;;;( e M [ d d ] N Q + = d d e )
;;;( e [ d d ] N Q + = d d e )
;;;( a M [ d d ] N Q + = d d a )
;;;( a [ d d ] N Q + = d d a )
;;;( o M [ d d ] N Q + = d d o )
;;;( o [ d d ] N Q + = d d o )
;;;( w M [ d d ] N Q + = d d w )
;;;( w [ d d ] N Q + = d d w )
;;;( u M [ d d ] N Q + = d d y )
;;;( u [ d d ] N Q + = d d y )
;;;( y M [ d d ] N Q + = d d y )
;;;( y [ d d ] N Q + = d d y )
;;;( i M [ d ] N Q + = d i )
;;;( i [ d ] N Q + = d i )
;;;( e M [ d ] N Q + = d e )
;;;( e [ d ] N Q + = d e )
;;;( a M [ d ] N Q + = d a )
;;;( a [ d ] N Q + = d a )
;;;( o M [ d ] N Q + = d o )
;;;( o [ d ] N Q + = d o )
;;;( w M [ d ] N Q + = d w )
;;;( w [ d ] N Q + = d w )
;;;( u M [ d ] N Q + = d y )
;;;( u [ d ] N Q + = d y )
;;;( y M [ d ] N Q + = d y )
;;;( y [ d ] N Q + = d y )
;;;( i M [ s ] N Q + = s i )
;;;( i [ s ] N Q + = s i )
;;;( e M [ s ] N Q + = s e )
;;;( e [ s ] N Q + = s e )
;;;( a M [ s ] N Q + = s a )
;;;( a [ s ] N Q + = s a )
;;;( o M [ s ] N Q + = s o )
;;;( o [ s ] N Q + = s o )
;;;( w M [ s ] N Q + = s w )
;;;( w [ s ] N Q + = s w )
;;;( u M [ s ] N Q + = s y )
;;;( u [ s ] N Q + = s y )
;;;( y M [ s ] N Q + = s y )
;;;( y [ s ] N Q + = s y )
;;;( i M [ s b ] N Q + = s b i )
;;;( i [ s b ] N Q + = s b i )
;;;( e M [ s b ] N Q + = s b e )
;;;( e [ s b ] N Q + = s b e )
;;;( a M [ s b ] N Q + = s b a )
;;;( a [ s b ] N Q + = s b a )
;;;( o M [ s b ] N Q + = s b o )
;;;( o [ s b ] N Q + = s b o )
;;;( w M [ s b ] N Q + = s b w )
;;;( w [ s b ] N Q + = s b w )
;;;( u M [ s b ] N Q + = s b y )
;;;( u [ s b ] N Q + = s b y )
;;;( y M [ s b ] N Q + = s b y )
;;;( y [ s b ] N Q + = s b y )
;;;( i M [ s t ] N Q + = s t i )
;;;( i [ s t ] N Q + = s t i )
;;;( e M [ s t ] N Q + = s t e )
;;;( e [ s t ] N Q + = s t e )
;;;( a M [ s t ] N Q + = s t a )
;;;( a [ s t ] N Q + = s t a )
;;;( o M [ s t ] N Q + = s t o )
;;;( o [ s t ] N Q + = s t o )
;;;( w M [ s t ] N Q + = s t w )
;;;( w [ s t ] N Q + = s t w )
;;;( u M [ s t ] N Q + = s t y )
;;;( u [ s t ] N Q + = s t y )
;;;( y M [ s t ] N Q + = s t y )
;;;( y [ s t ] N Q + = s t y )
;;;( i M [ s g ] N Q + = s g i )
;;;( i [ s g ] N Q + = s g i )
;;;( e M [ s g ] N Q + = s g e )
;;;( e [ s g ] N Q + = s g e )
;;;( a M [ s g ] N Q + = s g a )
;;;( a [ s g ] N Q + = s g a )
;;;( o M [ s g ] N Q + = s g o )
;;;( o [ s g ] N Q + = s g o )
;;;( w M [ s g ] N Q + = s g w )
;;;( w [ s g ] N Q + = s g w )
;;;( u M [ s g ] N Q + = s g y )
;;;( u [ s g ] N Q + = s g y )
;;;( y M [ s g ] N Q + = s g y )
;;;( y [ s g ] N Q + = s g y )
;;;( i M [ c h ] N Q + = c h i )
;;;( i [ c h ] N Q + = c h i )
;;;( e M [ c h ] N Q + = c h e )
;;;( e [ c h ] N Q + = c h e )
;;;( a M [ c h ] N Q + = c h a )
;;;( a [ c h ] N Q + = c h a )
;;;( o M [ c h ] N Q + = c h o )
;;;( o [ c h ] N Q + = c h o )
;;;( w M [ c h ] N Q + = c h w )
;;;( w [ c h ] N Q + = c h w )
;;;( u M [ c h ] N Q + = c h y )
;;;( u [ c h ] N Q + = c h y )
;;;( y M [ c h ] N Q + = c h y )
;;;( y [ c h ] N Q + = c h y )
;;;( i M [ c ] N Q + = c i )
;;;( i [ c ] N Q + = c i )
;;;( e M [ c ] N Q + = c e )
;;;( e [ c ] N Q + = c e )
;;;( a M [ c ] N Q + = c a )
;;;( a [ c ] N Q + = c a )
;;;( o M [ c ] N Q + = c o )
;;;( o [ c ] N Q + = c o )
;;;( w M [ c ] N Q + = c w )
;;;( w [ c ] N Q + = c w )
;;;( u M [ c ] N Q + = c y )
;;;( u [ c ] N Q + = c y )
;;;( y M [ c ] N Q + = c y )
;;;( y [ c ] N Q + = c y )
;;;( i M [ m ] N Q + = m i )
;;;( i [ m ] N Q + = m i )
;;;( e M [ m ] N Q + = m e )
;;;( e [ m ] N Q + = m e )
;;;( a M [ m ] N Q + = m a )
;;;( a [ m ] N Q + = m a )
;;;( o M [ m ] N Q + = m o )
;;;( o [ m ] N Q + = m o )
;;;( w M [ m ] N Q + = m w )
;;;( w [ m ] N Q + = m w )
;;;( u M [ m ] N Q + = m y )
;;;( u [ m ] N Q + = m y )
;;;( y M [ m ] N Q + = m y )
;;;( y [ m ] N Q + = m y )
;;;( i M [ n ] N Q + = n i )
;;;( i [ n ] N Q + = n i )
;;;( e M [ n ] N Q + = n e )
;;;( e [ n ] N Q + = n e )
;;;( a M [ n ] N Q + = n a )
;;;( a [ n ] N Q + = n a )
;;;( o M [ n ] N Q + = n o )
;;;( o [ n ] N Q + = n o )
;;;( w M [ n ] N Q + = n w )
;;;( w [ n ] N Q + = n w )
;;;( u M [ n ] N Q + = n y )
;;;( u [ n ] N Q + = n y )
;;;( y M [ n ] N Q + = n y )
;;;( y [ n ] N Q + = n y )
;;;( i M [ n g ] N Q + = n g i )
;;;( i [ n g ] N Q + = n g i )
;;;( e M [ n g ] N Q + = n g e )
;;;( e [ n g ] N Q + = n g e )
;;;( a M [ n g ] N Q + = n g a )
;;;( a [ n g ] N Q + = n g a )
;;;( o M [ n g ] N Q + = n g o )
;;;( o [ n g ] N Q + = n g o )
;;;( w M [ n g ] N Q + = n g w )
;;;( w [ n g ] N Q + = n g w )
;;;( u M [ n g ] N Q + = n g y )
;;;( u [ n g ] N Q + = n g y )
;;;( y M [ n g ] N Q + = n g y )
;;;( y [ n g ] N Q + = n g y )
;;;
;;;;;;  Repeat all cases, this time with "l K", to cut out cases of "l l"
;;;
;;;( o e M [ b ] l K + = b y )
;;;( o e [ b ] l K + = b y )
;;;( a e M [ b ] l K + = b y )
;;;( a e [ b ] l K + = b y )
;;;( o e M [ g ] l K + = g y )
;;;( o e [ g ] l K + = g y )
;;;( a e M [ g ] l K + = g y )
;;;( a e [ g ] l K + = g y )
;;;( o e M [ p ] l K + = p y )
;;;( o e [ p ] l K + = p y )
;;;( a e M [ p ] l K + = p y )
;;;( a e [ p ] l K + = p y )
;;;( o e M [ f f ] l K + = f f y )
;;;( o e [ f f ] l K + = f f y )
;;;( a e M [ f f ] l K + = f f y )
;;;( a e [ f f ] l K + = f f y )
;;;( o e M [ f ] l K + = f y )
;;;( o e [ f ] l K + = f y )
;;;( a e M [ f ] l K + = f y )
;;;( a e [ f ] l K + = f y )
;;;( o e M [ t h ] l K + = t h y )
;;;( o e [ t h ] l K + = t h y )
;;;( a e M [ t h ] l K + = t h y )
;;;( a e [ t h ] l K + = t h y )
;;;
;;;( o e M [ t ] l K + = t y )
;;;( o e [ t ] l K + = t y )
;;;( a e M [ t ] l K + = t y )
;;;( a e [ t ] l K + = t y )
;;;( o e l l [ t ] l K + = t y )
;;;( a e l l [ t ] l K + = t y )
;;;( o e M [ d d ] l K + = d d y )
;;;( o e [ d d ] l K + = d d y )
;;;( a e M [ d d ] l K + = d d y )
;;;( a e [ d d ] l K + = d d y )
;;;( o e M [ d ] l K + = d y )
;;;( o e [ d ] l K + = d y )
;;;( a e M [ d ] l K + = d y )
;;;( a e [ d ] l K + = d y )
;;;( o e M [ s ] l K + = s y )
;;;( o e [ s ] l K + = s y )
;;;( a e M [ s ] l K + = s y )
;;;( a e [ s ] l K + = s y )
;;;( o e M [ s b ] l K + = s b y )
;;;( o e [ s b ] l K + = s b y )
;;;( a e M [ s b ] l K + = s b y )
;;;( a e [ s b ] l K + = s b y )
;;;( o e M [ s t ] l K + = s t y )
;;;( o e [ s t ] l K + = s t y )
;;;( a e M [ s t ] l K + = s t y )
;;;( a e [ s t ] l K + = s t y )
;;;( o e M [ s g ] l K + = s g y )
;;;( o e [ s g ] l K + = s g y )
;;;( a e M [ s g ] l K + = s g y )
;;;( a e [ s g ] l K + = s g y )
;;;( o e M [ c h ] l K + = c h y )
;;;( o e [ c h ] l K + = c h y )
;;;( a e M [ c h ] l K + = c h y )
;;;( a e [ c h ] l K + = c h y )
;;;( o e M [ c ] l K + = c y )
;;;( o e [ c ] l K + = c y )
;;;( a e M [ c ] l K + = c y )
;;;( a e [ c ] l K + = c y )
;;;( o e M [ m ] l K + = m y )
;;;( o e [ m ] l K + = m y )
;;;( a e M [ m ] l K + = m y )
;;;( a e [ m ] l K + = m y )
;;;( o e M [ n ] l K + = n y )
;;;( o e [ n ] l K + = n y )
;;;( a e M [ n ] l K + = n y )
;;;( a e [ n ] l K + = n y )
;;;( o e M [ n g ] l K + = n g y )
;;;( o e [ n g ] l K + = n g y )
;;;( a e M [ n g ] l K + = n g y )
;;;( a e [ n g ] l K + = n g y )
;;;
;;;( i M [ b ] l K + = b i )
;;;( i [ b ] l K + = b i )
;;;( e M [ b ] l K + = b e )
;;;( e [ b ] l K + = b e )
;;;( a M [ b ] l K + = b a )
;;;( a [ b ] l K + = b a )
;;;( o M [ b ] l K + = b o )
;;;( o [ b ] l K + = b o )
;;;( w M [ b ] l K + = b w )
;;;( w [ b ] l K + = b w )
;;;( u M [ b ] l K + = b y )
;;;( u [ b ] l K + = b y )
;;;( y M [ b ] l K + = b y )
;;;( y [ b ] l K + = b y )
;;;( i M [ g ] l K + = g i )
;;;( i [ g ] l K + = g i )
;;;( e M [ g ] l K + = g e )
;;;( e [ g ] l K + = g e )
;;;( a M [ g ] l K + = g a )
;;;( a [ g ] l K + = g a )
;;;( o M [ g ] l K + = g o )
;;;( o [ g ] l K + = g o )
;;;( w M [ g ] l K + = g w )
;;;( w [ g ] l K + = g w )
;;;( u M [ g ] l K + = g y )
;;;( u [ g ] l K + = g y )
;;;( y M [ g ] l K + = g y )
;;;( y [ g ] l K + = g y )
;;;( i M [ p ] l K + = p i )
;;;( i [ p ] l K + = p i )
;;;( e M [ p ] l K + = p e )
;;;( e [ p ] l K + = p e )
;;;( a M [ p ] l K + = p a )
;;;( a [ p ] l K + = p a )
;;;( o M [ p ] l K + = p o )
;;;( o [ p ] l K + = p o )
;;;( w M [ p ] l K + = p w )
;;;( w [ p ] l K + = p w )
;;;( u M [ p ] l K + = p y )
;;;( u [ p ] l K + = p y )
;;;( y M [ p ] l K + = p y )
;;;( y [ p ] l K + = p y )
;;;( i M [ f f ] l K + = f f i )
;;;( i [ f f ] l K + = f f i )
;;;( e M [ f f ] l K + = f f e )
;;;( e [ f f ] l K + = f f e )
;;;( a M [ f f ] l K + = f f a )
;;;( a [ f f ] l K + = f f a )
;;;( o M [ f f ] l K + = f f o )
;;;( o [ f f ] l K + = f f o )
;;;( w M [ f f ] l K + = f f w )
;;;( w [ f f ] l K + = f f w )
;;;( u M [ f f ] l K + = f f y )
;;;( u [ f f ] l K + = f f y )
;;;( y M [ f f ] l K + = f f y )
;;;( y [ f f ] l K + = f f y )
;;;( i M [ f ] l K + = f i )
;;;( i [ f ] l K + = f i )
;;;( e M [ f ] l K + = f e )
;;;( e [ f ] l K + = f e )
;;;( a M [ f ] l K + = f a )
;;;( a [ f ] l K + = f a )
;;;( o M [ f ] l K + = f o )
;;;( o [ f ] l K + = f o )
;;;( w M [ f ] l K + = f w )
;;;( w [ f ] l K + = f w )
;;;( u M [ f ] l K + = f y )
;;;( u [ f ] l K + = f y )
;;;( y M [ f ] l K + = f y )
;;;( y [ f ] l K + = f y )
;;;( i M [ t h ] l K + = t h i )
;;;( i [ t h ] l K + = t h i )
;;;( e M [ t h ] l K + = t h e )
;;;( e [ t h ] l K + = t h e )
;;;( a M [ t h ] l K + = t h a )
;;;( a [ t h ] l K + = t h a )
;;;( o M [ t h ] l K + = t h o )
;;;( o [ t h ] l K + = t h o )
;;;( w M [ t h ] l K + = t h w )
;;;( w [ t h ] l K + = t h w )
;;;( u M [ t h ] l K + = t h y )
;;;( u [ t h ] l K + = t h y )
;;;( y M [ t h ] l K + = t h y )
;;;( y [ t h ] l K + = t h y )
;;;( i M [ t h ] m Q + = t h i )
;;;( i [ t h ] m Q + = t h i )
;;;( e M [ t h ] m Q + = t h e )
;;;( e [ t h ] m Q + = t h e )
;;;( a M [ t h ] m Q + = t h a )
;;;( a [ t h ] m Q + = t h a )
;;;( o M [ t h ] m Q + = t h o )
;;;( o [ t h ] m Q + = t h o )
;;;( w M [ t h ] m Q + = t h w )
;;;( w [ t h ] m Q + = t h w )
;;;( u M [ t h ] m Q + = t h y )
;;;( u [ t h ] m Q + = t h y )
;;;( y M [ t h ] m Q + = t h y )
;;;( y [ t h ] m Q + = t h y )
;;;( i M [ t ] l K + = t i )
;;;( i [ t ] l K + = t i )
;;;( e M [ t ] l K + = t e )
;;;( e [ t ] l K + = t e )
;;;( a M [ t ] l K + = t a )
;;;( a [ t ] l K + = t a )
;;;( o M [ t ] l K + = t o )
;;;( o [ t ] l K + = t o )
;;;( w M [ t ] l K + = t w )
;;;( w [ t ] l K + = t w )
;;;( u M [ t ] l K + = t y )
;;;( u [ t ] l K + = t y )
;;;( y M [ t ] l K + = t y )
;;;( y [ t ] l K + = t y )
;;;( i l l [ t ] l K + = t i )
;;;( e l l [ t ] l K + = t e )
;;;( a l l [ t ] l K + = t a )
;;;( o l l [ t ] l K + = t o )
;;;( w l l [ t ] l K + = t w )
;;;( u l l [ t ] l K + = t y )
;;;( y l l [ t ] l K + = t y )
;;;( i M [ d d ] l K + = d d i )
;;;( i [ d d ] l K + = d d i )
;;;( e M [ d d ] l K + = d d e )
;;;( e [ d d ] l K + = d d e )
;;;( a M [ d d ] l K + = d d a )
;;;( a [ d d ] l K + = d d a )
;;;( o M [ d d ] l K + = d d o )
;;;( o [ d d ] l K + = d d o )
;;;( w M [ d d ] l K + = d d w )
;;;( w [ d d ] l K + = d d w )
;;;( u M [ d d ] l K + = d d y )
;;;( u [ d d ] l K + = d d y )
;;;( y M [ d d ] l K + = d d y )
;;;( y [ d d ] l K + = d d y )
;;;( i M [ d ] l K + = d i )
;;;( i [ d ] l K + = d i )
;;;( e M [ d ] l K + = d e )
;;;( e [ d ] l K + = d e )
;;;( a M [ d ] l K + = d a )
;;;( a [ d ] l K + = d a )
;;;( o M [ d ] l K + = d o )
;;;( o [ d ] l K + = d o )
;;;( w M [ d ] l K + = d w )
;;;( w [ d ] l K + = d w )
;;;( u M [ d ] l K + = d y )
;;;( u [ d ] l K + = d y )
;;;( y M [ d ] l K + = d y )
;;;( y [ d ] l K + = d y )
;;;( i M [ s ] l K + = s i )
;;;( i [ s ] l K + = s i )
;;;( e M [ s ] l K + = s e )
;;;( e [ s ] l K + = s e )
;;;( a M [ s ] l K + = s a )
;;;( a [ s ] l K + = s a )
;;;( o M [ s ] l K + = s o )
;;;( o [ s ] l K + = s o )
;;;( w M [ s ] l K + = s w )
;;;( w [ s ] l K + = s w )
;;;( u M [ s ] l K + = s y )
;;;( u [ s ] l K + = s y )
;;;( y M [ s ] l K + = s y )
;;;( y [ s ] l K + = s y )
;;;( i M [ s b ] l K + = s b i )
;;;( i [ s b ] l K + = s b i )
;;;( e M [ s b ] l K + = s b e )
;;;( e [ s b ] l K + = s b e )
;;;( a M [ s b ] l K + = s b a )
;;;( a [ s b ] l K + = s b a )
;;;( o M [ s b ] l K + = s b o )
;;;( o [ s b ] l K + = s b o )
;;;( w M [ s b ] l K + = s b w )
;;;( w [ s b ] l K + = s b w )
;;;( u M [ s b ] l K + = s b y )
;;;( u [ s b ] l K + = s b y )
;;;( y M [ s b ] l K + = s b y )
;;;( y [ s b ] l K + = s b y )
;;;( i M [ s t ] l K + = s t i )
;;;( i [ s t ] l K + = s t i )
;;;( e M [ s t ] l K + = s t e )
;;;( e [ s t ] l K + = s t e )
;;;( a M [ s t ] l K + = s t a )
;;;( a [ s t ] l K + = s t a )
;;;( o M [ s t ] l K + = s t o )
;;;( o [ s t ] l K + = s t o )
;;;( w M [ s t ] l K + = s t w )
;;;( w [ s t ] l K + = s t w )
;;;( u M [ s t ] l K + = s t y )
;;;( u [ s t ] l K + = s t y )
;;;( y M [ s t ] l K + = s t y )
;;;( y [ s t ] l K + = s t y )
;;;( i M [ s g ] l K + = s g i )
;;;( i [ s g ] l K + = s g i )
;;;( e M [ s g ] l K + = s g e )
;;;( e [ s g ] l K + = s g e )
;;;( a M [ s g ] l K + = s g a )
;;;( a [ s g ] l K + = s g a )
;;;( o M [ s g ] l K + = s g o )
;;;( o [ s g ] l K + = s g o )
;;;( w M [ s g ] l K + = s g w )
;;;( w [ s g ] l K + = s g w )
;;;( u M [ s g ] l K + = s g y )
;;;( u [ s g ] l K + = s g y )
;;;( y M [ s g ] l K + = s g y )
;;;( y [ s g ] l K + = s g y )
;;;( i M [ c h ] l K + = c h i )
;;;( i [ c h ] l K + = c h i )
;;;( e M [ c h ] l K + = c h e )
;;;( e [ c h ] l K + = c h e )
;;;( a M [ c h ] l K + = c h a )
;;;( a [ c h ] l K + = c h a )
;;;( o M [ c h ] l K + = c h o )
;;;( o [ c h ] l K + = c h o )
;;;( w M [ c h ] l K + = c h w )
;;;( w [ c h ] l K + = c h w )
;;;( u M [ c h ] l K + = c h y )
;;;( u [ c h ] l K + = c h y )
;;;( y M [ c h ] l K + = c h y )
;;;( y [ c h ] l K + = c h y )
;;;( i M [ c ] l K + = c i )
;;;( i [ c ] l K + = c i )
;;;( e M [ c ] l K + = c e )
;;;( e [ c ] l K + = c e )
;;;( a M [ c ] l K + = c a )
;;;( a [ c ] l K + = c a )
;;;( o M [ c ] l K + = c o )
;;;( o [ c ] l K + = c o )
;;;( w M [ c ] l K + = c w )
;;;( w [ c ] l K + = c w )
;;;( u M [ c ] l K + = c y )
;;;( u [ c ] l K + = c y )
;;;( y M [ c ] l K + = c y )
;;;( y [ c ] l K + = c y )
;;;( i M [ m ] l K + = m i )
;;;( i [ m ] l K + = m i )
;;;( e M [ m ] l K + = m e )
;;;( e [ m ] l K + = m e )
;;;( a M [ m ] l K + = m a )
;;;( a [ m ] l K + = m a )
;;;( o M [ m ] l K + = m o )
;;;( o [ m ] l K + = m o )
;;;( w M [ m ] l K + = m w )
;;;( w [ m ] l K + = m w )
;;;( u M [ m ] l K + = m y )
;;;( u [ m ] l K + = m y )
;;;( y M [ m ] l K + = m y )
;;;( y [ m ] l K + = m y )
;;;( i M [ n ] l K + = n i )
;;;( i [ n ] l K + = n i )
;;;( e M [ n ] l K + = n e )
;;;( e [ n ] l K + = n e )
;;;( a M [ n ] l K + = n a )
;;;( a [ n ] l K + = n a )
;;;( o M [ n ] l K + = n o )
;;;( o [ n ] l K + = n o )
;;;( w M [ n ] l K + = n w )
;;;( w [ n ] l K + = n w )
;;;( u M [ n ] l K + = n y )
;;;( u [ n ] l K + = n y )
;;;( y M [ n ] l K + = n y )
;;;( y [ n ] l K + = n y )
;;;( i M [ n g ] l K + = n g i )
;;;( i [ n g ] l K + = n g i )
;;;( e M [ n g ] l K + = n g e )
;;;( e [ n g ] l K + = n g e )
;;;( a M [ n g ] l K + = n g a )
;;;( a [ n g ] l K + = n g a )
;;;( o M [ n g ] l K + = n g o )
;;;( o [ n g ] l K + = n g o )
;;;( w M [ n g ] l K + = n g w )
;;;( w [ n g ] l K + = n g w )
;;;( u M [ n g ] l K + = n g y )
;;;( u [ n g ] l K + = n g y )
;;;( y M [ n g ] l K + = n g y )
;;;( y [ n g ] l K + = n g y )


;      Add dummy diaeresis between paired vowels that don't form a diphthong

( [ a o ] = a "\"" o )
( [ e a ] = e "\"" a )
( [ e o ] = e "\"" o )
( [ o a ] = o "\"" a )
( [ u a ] = u "\"" a )
( [ u e ] = u "\"" e )
( [ u i ] = u "\"" i )
( [ u o ] = u "\"" o )

;         Dummy diaeresis rules for 'trwodd' etc.
( U Y R [ w i ] = w "\"" i )
( U Y R [ w e ] = w "\"" e )
( U Y R [ w a ] = w "\"" a )
( U Y R [ w o ] = w "\"" o )
( U Y R [ w u ] = w "\"" u )

( U Z h R [ w i ] = w "\"" i )
( U Z h R [ w e ] = w "\"" e )
( U Z h R [ w a ] = w "\"" a )
( U Z h R [ w o ] = w "\"" o )
( U Z h R [ w u ] = w "\"" u )

;;( U w [ i o ] = i "\"" o )
;;( U w [ i a ] = i "\"" a )
;;( U w [ i e ] = i "\"" e )
;;( U C + w [ i o ] = i "\"" o )
;;( U C + w [ i a ] = i "\"" a )
;;( U C + w [ i e ] = i "\"" e )
;;( U n g w [ i o ] = i "\"" o )
;;( U n g w [ i a ] = i "\"" a )
;;( U n g w [ i e ] = i "\"" e )
;;( U c h w [ i o ] = i "\"" o )
;;( U c h w [ i a ] = i "\"" a )
;;( U c h w [ i e ] = i "\"" e )
;;( U n g h w [ i o ] = i "\"" o )
;;( U n g h w [ i a ] = i "\"" a )
;;( U n g h w [ i e ] = i "\"" e )
;;
;;( V Q Q w [ i o ] = i "\"" o )
;;( V Q Q w [ i a ] = i "\"" a )
;;( V Q Q w [ i e ] = i "\"" e )
;;( V Q Q C + w [ i o ] = i "\"" o )
;;( V Q Q C + w [ i a ] = i "\"" a )
;;( V Q Q C + w [ i e ] = i "\"" e )
;;( V Q Q n g w [ i o ] = i "\"" o )
;;( V Q Q n g w [ i a ] = i "\"" a )
;;( V Q Q n g w [ i e ] = i "\"" e )
;;( V Q Q c h w [ i o ] = i "\"" o )
;;( V Q Q c h w [ i a ] = i "\"" a )
;;( V Q Q c h w [ i e ] = i "\"" e )
;;( V Q Q n g h w [ i o ] = i "\"" o )
;;( V Q Q n g h w [ i a ] = i "\"" a )
;;( V Q Q n g h w [ i e ] = i "\"" e )
;;
;;( U C + r [ i o ] = i "\"" o )
;;( U C + r [ i a ] = i "\"" a )
;;( U C + r [ i e ] = i "\"" e )
;;( U C + r h [ i o ] = i "\"" o )
;;( U C + r h [ i a ] = i "\"" a )
;;( U C + r h [ i e ] = i "\"" e )
;;( U C + l [ i o ] = i "\"" o )
;;( U C + l [ i a ] = i "\"" a )
;;( U C + l [ i e ] = i "\"" e )
;;( U C + m [ i o ] = i "\"" o )
;;( U C + m [ i a ] = i "\"" a )
;;( U C + m [ i e ] = i "\"" e )

;;( U d [ i o ] = i o )
;;( U d [ i a ] = i a )
;;( U d [ i e ] = i e )

;;( U C + M [ i o ] = i "\"" o )
;;( U C + [ i o ] = i "\"" o )
;;( U C + M [ i a ] = i "\"" a )
;;( U C + [ i a ] = i "\"" a )
;;( U C + M [ i e ] = i "\"" e )
;;( U C + [ i e ] = i "\"" e )
;;( U n g [ i o ] = i "\"" o )
;;( U n g [ i a ] = i "\"" a )
;;( U n g [ i e ] = i "\"" e )

;;( V Q Q r [ i o ] = i "\"" o )
;;( V Q Q r [ i a ] = i "\"" a )
;;( V Q Q r [ i e ] = i "\"" e )
;;( V Q Q r h [ i o ] = i "\"" o )
;;( V Q Q r h [ i a ] = i "\"" a )
;;( V Q Q r h [ i e ] = i "\"" e )
;;( V Q Q l [ i o ] = i "\"" o )
;;( V Q Q l [ i a ] = i "\"" a )
;;( V Q Q l [ i e ] = i "\"" e )
;;( V Q Q m [ i o ] = i "\"" o )
;;( V Q Q m [ i a ] = i "\"" a )
;;( V Q Q m [ i e ] = i "\"" e )

;;( V Q d [ i o ] = i o )
;;( V Q d [ i a ] = i a )
;;( V Q d [ i e ] = i e )

;;( V Q Q M [ i o ] = i "\"" o )
;;( V Q Q [ i o ] = i "\"" o )
;;( V Q Q M [ i a ] = i "\"" a )
;;( V Q Q [ i a ] = i "\"" a )
;;( V Q Q M [ i e ] = i "\"" e )
;;( V Q Q [ i e ] = i "\"" e )
;;( V Q Q n g [ i o ] = i "\"" o )
;;( V Q Q n g [ i a ] = i "\"" a )
;;( V Q Q n g [ i e ] = i "\"" e )

;             Labialised liquid rules to sort out the syllable count
( U g [ w ] R X C + = q )
( U n g [ w ] R X C + = q )
( U [ w ] R X C + = q )
;       Hard-wire in some morphemic information
( V C + [ w ] r a i g U = q )
( V C + [ w ] r a g e d d U = q )
( V C + [ w ] r e i n e n U = q )
( V C + [ w ] r e i n y n U = q )
( V C + [ w ] r e i g i a e t h U = q )
( V C + [ w ] r e i c i a e t h U = q )
( V C + [ w ] l a d U = q )
( V C + [ w ] l e d y d d U = q )
( V C + [ w ] n e u d U = q )
( V C + [ w ] n e u t h u r U = q )
( U d a d [ w ] R V = q )
( U g o r [ w ] R V = q )
( U r h y n g [ w ] R V = q )

;    Dummy diaeresis rules to pre-empt i-to-yod rules later on,
;    in situations where the 'i' is preceded by an epenthesis context 
;    ( V a e i o u y )
;    ( M l m n r )
;    ( F l n r f )

;;( V M V F [ i ] V = i "\"" )
;;( V V F [ i ] V = i "\"" )
( V l l t F [ i ] V = i "\"" )
( V M t h m [ i ] V = i "\"" )
( V t h m [ i ] V = i "\"" )

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                                                                        ;;
;;  This section contains the rules converting "i" to yod (palatal glide) ;;
;;  using the same contexts as are used in the next module (assignment of ;;
;;  stress) to decode vowels after yod.                                   ;;
;;       Added by BJW in December 2005                                    ;;
;;                                                                        ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;    Accent-marked monophthongs and diphthongs after yod:
( U A * [ i ] a / A * U = J )
( U A * [ i ] e / A * U = J )
( U A * [ i ] o / A * U = J )
( U A * [ i ] a "\\" A * U = J )
( U A * [ i ] e "\\" A * U = J )
( U A * [ i ] o "\\" A * U = J )

;    Non-accent marked monophthongs and dipthongs after yod:
;   Versions for preceding vocalic 'w' (which look like a monosyll to the rules):
;   With two intervening consonants:
( U G * w S S [ i ] a "'" i G * U = J )
( U G * w S S [ i ] a i G * U = J )
( U G * w S S [ i ] a e G * U = J )
( U G * w S S [ i ] a "'" u G * U = J )
( U G * w S S [ i ] a u G * U = J )
( U G * w S S [ i ] a "'" w G * U = J )
( U G * w S S [ i ] a w G * U = J )
( U G * w S S [ i ] a ^ G * U = J )
( U G * w S S [ i ] a "+" G * U = J )
( U G * w S S [ i ] a G * U = J a )
( U G * w S S [ i ] e w G * U = J )
( U G * w S S [ i ] e "'" i G * U = J )
( U G * w S S [ i ] e i G * U = J )
( U G * w S S [ i ] e y G * U = J )
( U G * w S S [ i ] e "'" u G * U = J )
( U G * w S S [ i ] e u G * U = J )
( U G * w S S [ i ] e ^ G * U = J )
( U G * w S S [ i ] e "+" G * U = J )
( U G * w S S [ i ] e G * U = J )
( U G * w S S [ i ] o y G * U = J )
( U G * w S S [ i ] o "'" u G * U = J )
( U G * w S S [ i ] o u G * U = J )
( U G * w S S [ i ] o e G * U = J )
( U G * w S S [ i ] o w G * U = J )
( U G * w S S [ i ] o ^ G * U = J )
( U G * w S S [ i ] o "+" G * U = J )
( U G * w S S [ i ] o G * U = J )
;   With one intervening consonant:
( U G * w S [ i ] a "'" i G * U = J )
( U G * w S [ i ] a i G * U = J )
( U G * w S [ i ] a e G * U = J )
( U G * w S [ i ] a "'" u G * U = J )
( U G * w S [ i ] a u G * U = J )
( U G * w S [ i ] a "'" w G * U = J )
( U G * w S [ i ] a w G * U = J )
( U G * w S [ i ] a ^ G * U = J )
( U G * w S [ i ] a "+" G * U = J )
( U G * w S [ i ] a G * U = J )
( U G * w S [ i ] e w G * U = J )
( U G * w S [ i ] e "'" i G * U = J )
( U G * w S [ i ] e i G * U = J )
( U G * w S [ i ] e y G * U = J )
( U G * w S [ i ] e "'" u G * U = J )
( U G * w S [ i ] e u G * U = J )
( U G * w S [ i ] e ^ G * U = J )
( U G * w S [ i ] e "+" G * U = J )
( U G * w S [ i ] e G * U = J )
( U G * w S [ i ] o y G * U = J )
( U G * w S [ i ] o "'" u G * U = J )
( U G * w S [ i ] o u G * U = J )
( U G * w S [ i ] o e G * U = J )
( U G * w S [ i ] o w G * U = J )
( U G * w S [ i ] o ^ G * U = J )
( U G * w S [ i ] o "+" G * U = J )
( U G * w S [ i ] o G * U = J )

;    Default versions:  no preceding vocalic 'w':
( U A * [ i ] a "'" i A * U = J )
( U A * [ i ] a i A * U = J )
( U A * [ i ] a e A * U = J )
( U A * [ i ] a "'" u A * U = J )
( U A * [ i ] a u A * U = J )
( U A * [ i ] a "'" w A * U = J )
( U A * [ i ] a w A * U = J )
( U A * [ i ] a ^ A * U = J )
( U A * [ i ] a "+" A * U = J )
( U A * [ i ] a A * U = J )
( U A * [ i ] e w A * U = J )
( U A * [ i ] e "'" i A * U = J )
( U A * [ i ] e i A * U = J )
( U A * [ i ] e y A * U = J )
( U A * [ i ] e "'" u A * U = J )
( U A * [ i ] e u A * U = J )
( U A * [ i ] e ^ A * U = J )
( U A * [ i ] e "+" A * U = J )
( U A * [ i ] e A * U = J )
( U A * [ i ] o y A * U = J )
( U A * [ i ] o "'" u A * U = J )
( U A * [ i ] o u A * U = J )
( U A * [ i ] o e A * U = J )
( U A * [ i ] o w A * U = J )
( U A * [ i ] o ^ A * U = J )
( U A * [ i ] o "+" A * U = J )
( U A * [ i ] o A * U = J )

( [ i ] a G * w / = J )
( [ i ] e G * w / = J )
( [ i ] o G * w / = J )

( [ i ] a A * V + / = J )
( [ i ] e A * V + / = J )
( [ i ] o A * V + / = J )

( [ i ] a G * w ^ = J )
( [ i ] a G * w "+" = J )
( [ i ] e G * w ^ = J )
( [ i ] e G * w "+" = J )
( [ i ] o G * w ^ = J )
( [ i ] o G * w "+" = J )

( [ i ] a A * T + ^ = J )
( [ i ] a A * T + "+" = J )
( [ i ] e A * T + ^ = J )
( [ i ] e A * T + "+" = J )
( [ i ] o A * T + ^ = J )
( [ i ] o A * T + "+" = J )

( / A * [ i ] a G * w A * U = J )
( / A * [ i ] e G * w A * U = J )
( / A * [ i ] o G * w A * U = J )

( / A * [ i ] a A * T + A * U = J )
( / A * [ i ] e A * T + A * U = J )
( / A * [ i ] o A * T + A * U = J )

;    Versions where intervening cons is yod (2nd vowel therefore not 'w'):
;    V = 1 or more of  a|e|i|o|u|w|y ;  L = 1 or more of  a|e|i|o|u|y (no 'w')
;     I = 1 of a | e | o 
( o [ i ] I A * U = J )
( a [ i ] I A * U = J )
( e [ i ] I A * U = J )
( o [ i ] I L + A * U = J )
( a [ i ] I L + A * U = J )
( e [ i ] I L + A * U = J )
( w ^ y [ i ] I A * U = J )
( w "+" y [ i ] I A * U = J )
( w y ^ [ i ] I A * U = J )
( w y "+" [ i ] I A * U = J )
( w ^ y [ i ] I L + A * U = J )
( w "+" y [ i ] I L + A * U = J )
( w y ^ [ i ] I L + A * U = J )
( w y "+" [ i ] I L + A * U = J )

;     Versions where no consonant intervenes:
( o [ i ] I A * U = J )
( a [ i ] I A * U = J )
( e [ i ] I A * U = J )


( [ i ] a u U = J )
( [ i ] I D * A * U = J )
( [ i ] I "'" T + A * U = J )
( [ i ] I ^ T + A * U = J )
( [ i ] I "+" T + A * U = J )

;   'i-plus-single-vowel' in penult:
( [ i ] a E + w A * U = J )
( [ i ] e E + w A * U = J )
( [ i ] o E + w A * U = J )
;   Where string is trisyllabic with 'w' in ultima:
( [ i ] a E + T + E + w A * U = J )
( [ i ] e E + T + E + w A * U = J )
( [ i ] o E + T + E + w A * U = J )
;    Default versions:
( [ i ] a B A * T + A * U = J )
( [ i ] e B A * T + A * U = J )
( [ i ] o B A * T + A * U = J )


;   g)  Vowels in unstressed ultimas, antepenults (default), & unstressed penults
;     Sequences of three vowel graphemes
( [ o i ] V + C * = o J )
( [ a i ] V + C * = a J )

( o [ i ] T + A * = J )
( a [ i ] T + A * = J )

( e [ i ] T + A * = J )

( [ i ] a = J )
( [ i ] e = J )
( [ i ] o = J )

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; 	Let all other graphemes pass through unchanged

;            (k,q,v,x,z: in English alphabet but not Welsh:
;             added anyway, to deal with any English words)
( [ a ] = a )
( [ b ] = b )
( [ c ] = c )
( [ d ] = d )
( [ e ] = e )
( [ f ] = f )
( [ g ] = g )
( [ h ] = h )
( [ i ] = i )
( [ j ] = j )
( [ l ] = l )
( [ m ] = m )
( [ n ] = n )
( [ o ] = o )
( [ p ] = p )
( [ r ] = r )
( [ s ] = s )
( [ t ] = t )
( [ u ] = u )
( [ w ] = w )
( [ y ] = y )
( [ k ] = k )
( [ q ] = q )
( [ v ] = v )
( [ x ] = x )
( [ z ] = z )
( [ ^ ] = ^ )
( [ "+" ] = ^ )
( [ "\\" ] = "\\" )
( [ "/" ] = "/" )

;    Allow for eg. "amgaee%dig" where diaeresis is on 'wrong' vowel grapheme
( V V [ e "%" ] C + = "\"" e )

;    Allow input % to be read as diaeresis
( [ "%" ] = "\"" )
))

(provide 'gogepen)


